import type { EmotionData, EmotionLabel, FaqItem, SessionRecord } from "@/types";

export const EMOTION_COLORS: Record<EmotionLabel, string> = {
  Happy: "#f59e0b",
  Calm: "#38bdf8",
  Neutral: "#6b7280",
  Fearful: "#a78bfa",
  Angry: "#ef4444",
  Surprised: "#ec4899",
};

export const DEMO_EMOTION_DATA: EmotionData[] = [
  {
    voice: "Calm",
    words: "Calm",
    face: "Calm",
    combined: "Calm",
    voicePct: 70,
    wordsPct: 80,
    facePct: 85,
    combinedPct: 78,
    color: "#38bdf8",
  },
  {
    voice: "Calm",
    words: "Calm",
    face: "Fearful",
    combined: "Calm",
    voicePct: 65,
    wordsPct: 70,
    facePct: 39,
    combinedPct: 62,
    color: "#38bdf8",
  },
  {
    voice: "Calm",
    words: "Calm",
    face: "Fearful",
    combined: "Calm",
    voicePct: 60,
    wordsPct: 72,
    facePct: 35,
    combinedPct: 58,
    color: "#38bdf8",
  },
  {
    voice: "Calm",
    words: "Calm",
    face: "Angry",
    combined: "Calm",
    voicePct: 68,
    wordsPct: 75,
    facePct: 42,
    combinedPct: 65,
    color: "#38bdf8",
  },
  {
    voice: "Calm",
    words: "Calm",
    face: "Happy",
    combined: "Calm",
    voicePct: 72,
    wordsPct: 80,
    facePct: 75,
    combinedPct: 75,
    color: "#38bdf8",
  },
  {
    voice: "Happy",
    words: "Happy",
    face: "Surprised",
    combined: "Happy",
    voicePct: 80,
    wordsPct: 78,
    facePct: 45,
    combinedPct: 72,
    color: "#f59e0b",
  },
  {
    voice: "Happy",
    words: "Happy",
    face: "Happy",
    combined: "Happy",
    voicePct: 85,
    wordsPct: 85,
    facePct: 80,
    combinedPct: 82,
    color: "#f59e0b",
  },
  {
    voice: "Calm",
    words: "Calm",
    face: "Calm",
    combined: "Calm",
    voicePct: 75,
    wordsPct: 73,
    facePct: 70,
    combinedPct: 73,
    color: "#38bdf8",
  },
];

export const SESSIONS_DATA: SessionRecord[] = [
  {
    id: 1,
    type: "live",
    icon: "target",
    title: "Pitch Practice",
    date: "Today, 14:22",
    duration: "12m 34s",
    emotion: "Happy",
    emotionPct: 85,
    tone: "Happy",
    tonePct: 90,
    words: "Happy",
    wordsPct: 80,
    face: "Surprised",
    facePct: 40,
  },
  {
    id: 2,
    type: "offline",
    icon: "video",
    title: "Interview Recording Analysis",
    date: "Today, 11:05",
    duration: "1m 16s",
    emotion: "Calm",
    emotionPct: 78,
    tone: "Calm",
    tonePct: 70,
    words: "Calm",
    wordsPct: 80,
    face: "Calm",
    facePct: 85,
  },
  {
    id: 3,
    type: "live",
    icon: "chat",
    title: "Investor Q&A Session",
    date: "Yesterday, 16:40",
    duration: "8m 12s",
    emotion: "Neutral",
    emotionPct: 60,
    tone: "Calm",
    tonePct: 65,
    words: "Neutral",
    wordsPct: 58,
    face: "Fearful",
    facePct: 35,
  },
  {
    id: 4,
    type: "live",
    icon: "users",
    title: "Difficult Conversations",
    date: "Yesterday, 09:18",
    duration: "15m 02s",
    emotion: "Calm",
    emotionPct: 72,
    tone: "Calm",
    tonePct: 75,
    words: "Calm",
    wordsPct: 70,
    face: "Calm",
    facePct: 70,
  },
  {
    id: 5,
    type: "offline",
    icon: "video",
    title: "Presentation Review",
    date: "Mar 12, 17:30",
    duration: "4m 48s",
    emotion: "Happy",
    emotionPct: 80,
    tone: "Happy",
    tonePct: 82,
    words: "Happy",
    wordsPct: 78,
    face: "Happy",
    facePct: 80,
  },
  {
    id: 6,
    type: "live",
    icon: "heart",
    title: "Heart-to-Heart Check-in",
    date: "Mar 11, 20:10",
    duration: "22m 55s",
    emotion: "Neutral",
    emotionPct: 55,
    tone: "Neutral",
    tonePct: 50,
    words: "Calm",
    wordsPct: 60,
    face: "Neutral",
    facePct: 55,
  },
];

export const FAQS_DATA: FaqItem[] = [
  {
    tag: "Emotion AI",
    question: "How does Nearu detect emotions?",
    answer:
      "Nearu analyzes three independent channels simultaneously: acoustic emotion (voice prosody — tone, pitch, pace, tremor), semantic emotion (meaning behind the words), and facial emotion (micro-expressions via camera frames). Each channel produces a label and confidence score, which are then fused into a single interpreted emotional state.",
  },
  {
    tag: "Privacy",
    question: "Is my camera footage stored anywhere?",
    answer:
      "No. Camera frames are processed locally for facial emotion extraction and immediately discarded. They are never stored on Nearu servers and never used for training. Only emotion labels and session transcripts are saved if you have conversation history enabled.",
  },
  {
    tag: "Getting Started",
    question: "What is the difference between Live Session and Offline Analysis?",
    answer:
      "Live Session enables real-time conversation with the Nearu avatar — emotion is analyzed as you speak. Offline Analysis lets you upload a pre-recorded video (an interview, presentation, or meeting recording) and get a full emotion timeline breakdown after processing.",
  },
  {
    tag: "Emotion AI",
    question: "How accurate is the emotion detection?",
    answer:
      "Nearu uses a confidence-weighted fusion approach. The system never reports neutral unless all available signals genuinely indicate neutral. When channels conflict (e.g. calm words but anxious voice), acoustic signals take priority — how you say something reveals more than what you say.",
  },
  {
    tag: "Privacy",
    question: "What data is saved between sessions?",
    answer:
      'If "Save conversation history" is enabled in Settings, Nearu saves transcripts and emotion summaries per session. Raw audio and video are never persisted. You can clear session data or all memory at any time from the Settings page.',
  },
  {
    tag: "Getting Started",
    question: "What video formats are supported for Offline Analysis?",
    answer:
      "MP4, MOV, and WebM files up to 500MB. For best results, use recordings with clear audio and good lighting. The analysis pipeline processes both audio tracks and visual frames automatically.",
  },
  {
    tag: "Technical",
    question: "What is the processing latency for emotion analysis?",
    answer:
      "For live sessions, emotion analysis runs in approximately 1.6–2.5 seconds end-to-end per turn. Offline video analysis time depends on video length — typically 10–30 seconds for videos under 5 minutes.",
  },
  {
    tag: "Technical",
    question: "Can I use Nearu without a camera?",
    answer:
      "Yes. The API is signal-agnostic. If no camera frames are provided, Nearu returns acoustic and semantic emotion only. Face signal is excluded entirely — the system never pads missing data with neutral defaults.",
  },
];

export const ICON_SVG_MAP: Record<string, string> = {
  target:
    '<svg width="16" height="16" fill="none" stroke="currentColor" viewBox="0 0 24 24"><circle cx="12" cy="12" r="10"/><circle cx="12" cy="12" r="3"/></svg>',
  video:
    '<svg width="16" height="16" fill="none" stroke="currentColor" viewBox="0 0 24 24"><rect x="3" y="3" width="18" height="14" rx="2"/><path d="M7 21h10M12 17v4"/></svg>',
  chat:
    '<svg width="16" height="16" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path d="M21 15a2 2 0 0 1-2 2H7l-4 4V5a2 2 0 0 1 2-2h14a2 2 0 0 1 2 2z"/></svg>',
  users:
    '<svg width="16" height="16" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path d="M17 21v-2a4 4 0 0 0-4-4H5a4 4 0 0 0-4 4v2"/><circle cx="9" cy="7" r="4"/><path d="M23 21v-2a4 4 0 0 0-3-3.87M16 3.13a4 4 0 0 1 0 7.75"/></svg>',
  heart:
    '<svg width="16" height="16" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path d="M20.84 4.61a5.5 5.5 0 0 0-7.78 0L12 5.67l-1.06-1.06a5.5 5.5 0 0 0-7.78 7.78l1.06 1.06L12 21.23l7.78-7.78 1.06-1.06a5.5 5.5 0 0 0 0-7.78z"/></svg>',
};
